from fpdf import FPDF
import tempfile

class DistrictReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.set_text_color(50, 50, 50)
        self.cell(0, 10, 'UrbanSight AI - District Analysis Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, label):
        self.set_font('Helvetica', 'B', 12)
        self.set_fill_color(240, 240, 240)
        self.cell(0, 10, label, 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        self.set_font('Helvetica', '', 11)
        self.multi_cell(0, 6, body)
        self.ln()

def generate_pdf(district_name, stats, insights):
    """
    Generates a PDF report for a specific district.
    
    Args:
        district_name (str): Name of the district.
        stats (dict): Dictionary containing numerical stats (NDVI, NDBI, risk).
        insights (list): List of string insights or bullets.
        
    Returns:
        bytes: PDF content as bytes.
    """
    pdf = DistrictReport()
    pdf.add_page()
    
    # Title Section
    pdf.set_font('Helvetica', 'B', 16)
    pdf.cell(0, 10, f'Report for Sector: {district_name}', 0, 1)
    pdf.ln(5)
    
    # Key Metrics
    pdf.chapter_title('Key Environmental Metrics')
    
    pdf.set_font('Helvetica', '', 11)
    # create a simple table-like structure using cells
    col_width = pdf.w / 4
    
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(col_width, 10, 'Metric', 1)
    pdf.cell(col_width, 10, 'Value', 1)
    pdf.cell(col_width*2, 10, 'Interpretation', 1)
    pdf.ln()
    
    pdf.set_font('Helvetica', '', 11)
    
    # NDVI Row
    pdf.cell(col_width, 10, 'Mean NDVI', 1)
    pdf.cell(col_width, 10, f"{stats.get('mean_ndvi', 0):.2f}", 1)
    pdf.cell(col_width*2, 10, stats.get('ndvi_desc', 'N/A'), 1)
    pdf.ln()

    # NDBI Row
    pdf.cell(col_width, 10, 'Mean NDBI', 1)
    pdf.cell(col_width, 10, f"{stats.get('mean_ndbi', 0):.2f}", 1)
    pdf.cell(col_width*2, 10, stats.get('ndbi_desc', 'N/A'), 1)
    pdf.ln()

    # Risk Row
    pdf.cell(col_width, 10, 'Sprawl Risk', 1)
    pdf.cell(col_width, 10, f"{stats.get('sprawl_risk', 0):.1f}%", 1)
    pdf.cell(col_width*2, 10, stats.get('risk_desc', 'N/A'), 1)
    pdf.ln()
    
    pdf.ln(10)
    
    # Insights Section
    pdf.chapter_title('AI Analysis & Projections')
    for insight in insights:
        pdf.cell(5) # indent
        pdf.cell(0, 6, f"- {insight}", 0, 1)
    
    pdf.ln(10)
    pdf.set_font('Helvetica', 'I', 10)
    pdf.write(5, "This report was auto-generated by UrbanSight AI. Data derived from Sentinel-2 satellite telemetry.")
    
    # Output to bytes
    return bytes(pdf.output(dest='S'))
